{
 "title": "COVID-19 - Analisi Italia",
 "description": "Coronavirus (COVID-19) - Statistiche Italia",
 "tags": [
  "covid",
  "covid19",
  "covid-19",
  "covid-italy",
  "coronavirus"
 ],
 "time": { "from": "2020-02-22T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Regione",
    "label": "Seleziona regione",
    "query": "select distinct denominazione_regione from covid19.province"
   }
  ]
 },
 "panels": [
  { "title": "Ultimo aggiornamento", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Ultimo aggiornamento dati",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(MAX(data), \"%d-%m-%Y\") as \"last_data\" FROM nazionale"
    }
   ]
  },
  {
   "title": "Ultimo tempo di raddoppio dei contagi registrato (giorni)",
   "type": "stat",
   "description": "Il valore riportato indica, utilizzando i dati disponibili (quindi senza considerare ipotetici trend futuri), l'ultimo tempo di raddoppio (in giorni, a partire da oggi) in cui il numero degli \"attualmente positivi\" è raddoppiato.\nPerciò, per esempio, se fosse riportato un valore di 5, significherebbe che negli ultimi 5 giorni il numero degli \"attualmente positivi\" è raddoppiato.",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT CURDATE() as \"time\", tempo_raddoppio as \"Ultimo tempo di raddoppio registrato dei contagi (giorni)\" FROM statistiche"
    }
   ]
  },
  {
   "title": "Ultima variazione dei decessi",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCURDATE() as \"time\",\ntoday.deceduti-yesterday.deceduti as \"Decessi (OGGI)\",\nyesterday.deceduti-before_yesterday.deceduti as \"Decessi (IERI)\",\n(today.deceduti-yesterday.deceduti)-(yesterday.deceduti-before_yesterday.deceduti) as \"Incremento decessi giornalieri (OGGI)\"\nFROM nazionale today, nazionale yesterday, nazionale before_yesterday\nWHERE SUBDATE(today.data, 1) = yesterday.data AND today.data = (SELECT MAX(data) from nazionale) AND before_yesterday.data = SUBDATE(yesterday.data, 1)"
    }
   ]
  },
  {
   "title": "Ultima variazione del conteggio dei positivi",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCURDATE() as \"time\",\ntoday.nuovi_positivi as \"Nuovi positivi (OGGI)\",\nyesterday.nuovi_positivi as \"Nuovi positivi (IERI)\", \ntoday.nuovi_positivi-yesterday.nuovi_positivi as \"Incremento nuovi positivi giornalieri (OGGI)\"\nFROM nazionale today, nazionale yesterday\nWHERE SUBDATE(today.data, 1) = yesterday.data AND today.data = (SELECT MAX(data) from nazionale)"
    }
   ]
  },
  {
   "title": "Ultima variazione del conteggio dei guariti",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCURDATE() as \"time\",\ntoday.dimessi_guariti-yesterday.dimessi_guariti as \"Guariti (OGGI)\",\nyesterday.dimessi_guariti-before_yesterday.dimessi_guariti as \"Guariti (IERI)\",\n(today.dimessi_guariti-yesterday.dimessi_guariti)-(yesterday.dimessi_guariti-before_yesterday.dimessi_guariti) as \"Incremento guariti giornalieri (OGGI)\"\nFROM nazionale today, nazionale yesterday, nazionale before_yesterday\nWHERE SUBDATE(today.data, 1) = yesterday.data AND today.data = (SELECT MAX(data) from nazionale) AND before_yesterday.data = SUBDATE(yesterday.data, 1)"
    }
   ]
  },
  {
   "title": "Ultima variazione dei ricoveri in terapia intensiva",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCURDATE() as \"time\",\ntoday.terapia_intensiva as \"Totale ricoverati in terapia intensiva (OGGI)\",\ntoday.terapia_intensiva-yesterday.terapia_intensiva as \"Incremento posti occupati (OGGI)\",\ntoday.ingressi_terapia_intensiva as \"Nuovi ingressi in terapia intensiva (OGGI)\",\ntoday.ingressi_terapia_intensiva-yesterday.ingressi_terapia_intensiva as \"Incremento ingressi in terapia intensiva (OGGI)\",\nyesterday.terapia_intensiva as \"Totale ricoverati in terapia intensiva (IERI)\", \nyesterday.ingressi_terapia_intensiva as \"Nuovi ingressi in terapia intensiva (IERI)\"\n\nFROM nazionale today, nazionale yesterday\nWHERE SUBDATE(today.data, 1) = yesterday.data AND today.data = (SELECT MAX(data) from nazionale)"
    }
   ]
  },
  {
   "title": "Ultima variazione del numero di tamponi effettuati e rapporto positivi/tamponi ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \nCURDATE() as \"time\",\ntoday.nuovi_positivi/(today.tamponi-yesterday.tamponi) * 100 as \"Rapporto (%) positivi/tamponi (OGGI)\",\ntoday.tamponi-yesterday.tamponi as \"Tamponi (OGGI)\",\nyesterday.nuovi_positivi/(yesterday.tamponi-before_yesterday.tamponi) * 100 as \"Rapporto (%) positivi/tamponi (IERI)\",\nyesterday.tamponi-before_yesterday.tamponi as \"Tamponi (IERI)\",\n(today.tamponi-yesterday.tamponi)-(yesterday.tamponi-before_yesterday.tamponi) as \"Incremento tamponi (OGGI)\"\nFROM nazionale today, nazionale yesterday, nazionale before_yesterday\nWHERE SUBDATE(today.data, 1) = yesterday.data AND today.data = (SELECT MAX(data) from nazionale) AND before_yesterday.data = SUBDATE(yesterday.data, 1)"
    }
   ]
  },
  {
   "title": "Totale infetti per regione (da inizio epidemia)",
   "type": "graph",
   "description": "Il grafico mostra per ogni regione i casi totali di contagio registrati dall'inizio dell'epidemia",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  denominazione_regione AS metric,\n  sum(totale_casi)\nFROM covid19.province\ngroup by denominazione_regione, data\nORDER BY data, denominazione_regione"
    }
   ]
  },
  {
   "title": "Vaccini somministrati",
   "type": "gauge",
   "description": "Dosi di vaccino somministrate e consegnate a livello nazionale",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(dosi_somministrate) as \"Dosi somministrate\",\n  SUM(dosi_consegnate) as \"Dosi consegnate\",\n  (SUM(dosi_somministrate)/SUM(dosi_consegnate))*100 as \"Percentuale dosi somministrate/consegnate\"\nFROM \nsomministrazioni_summary\nWHERE\nultimo_aggiornamento = (SELECT max(ultimo_aggiornamento) from somministrazioni_summary)"
    },
    {
     "rawSql": "SELECT\n  SUM(seconda_dose)+(SELECT SUM(prima_dose) FROM somministrazioni_fasce WHERE fornitore='Janssen') as \"Persone immunizzate\"\nfrom\n  somministrazioni_fasce"
    }
   ]
  },
  {
   "title": "Vaccini somministrati per regione (SELEZIONA REGIONE)",
   "type": "gauge",
   "description": "Dosi di vaccino somministrate e consegnate a livello regionale",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(dosi_somministrate) as \"Dosi somministrate\",\n  SUM(dosi_consegnate) as \"Dosi consegnate\",\n  (SUM(dosi_somministrate)/SUM(dosi_consegnate))*100 as \"Percentuale dosi somministrate/consegnate\"\nFROM \nsomministrazioni_summary, dati_statici\nWHERE\nultimo_aggiornamento = (SELECT max(ultimo_aggiornamento) from somministrazioni_summary) AND somministrazioni_summary.area = dati_statici.area AND dati_statici.regione = '$Regione'"
    },
    {
     "rawSql": "select\nsum(seconda_dose)+(SELECT SUM(prima_dose) FROM somministrazioni_fasce, dati_statici WHERE somministrazioni_fasce.area = dati_statici.area AND dati_statici.regione = '$Regione' AND fornitore='Janssen') as \"Persone immunizzate\"\nfrom \nsomministrazioni_fasce, dati_statici\nwhere \nsomministrazioni_fasce.area = dati_statici.area AND dati_statici.regione = '$Regione'"
    }
   ]
  },
  {
   "title": "Categorie di vaccinati per regione (SELEZIONA REGIONE)",
   "type": "stat",
   "description": "Per ogni categoria è mostrato il numero di vaccini effettuati per la fascia/categoria corrispondente",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  now() AS \"time\",\n  sum(sesso_maschile) as \"Maschi\",\n  sum(sesso_femminile) as \"Femmine\"\nFROM somministrazioni, dati_statici\nWHERE somministrazioni.area = dati_statici.area AND dati_statici.regione = '$Regione'\n"
    }
   ]
  },
  {
   "title": "Situazione giornaliera positivi per regione - SELEZIONARE REGIONE",
   "type": "graph",
   "description": "Per ogni regione, è riportato il numero  di casi in isolamento domiciliare, ricoverati con sintomi e in terapia intensiva (report giornaliero)",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  isolamento_domiciliare AS \"Isolamento domicialiare\",\n  ricoverati_con_sintomi AS \"Ricoverati con sintomi\",\n  terapia_intensiva AS \"Terapia intensiva\"\nFROM regioni\nWHERE denominazione_regione='$Regione'"
    }
   ]
  },
  {
   "title": "Grafici regionali (SELEZIONARE REGIONE IN ALTO)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 }
  },
  {
   "title": "Totale infetti per provincia (da inizio epidemia) - SELEZIONA REGIONE",
   "type": "graph",
   "description": "Per ogni regione e per ogni provincia, è riportato il numero totale di casi tracciati dall'inizio dell'epidemia",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  denominazione_provincia AS metric,\n  sum(totale_casi)\nFROM covid19.province\nwhere denominazione_regione='$Regione'\ngroup by denominazione_provincia, data\nORDER BY data, denominazione_provincia"
    }
   ]
  },
  {
   "title": "Test e positivi regionali  giornalieri per tamponi rapidi e molecolari - SELEZIONA REGIONE",
   "type": "graph",
   "description": "Il grafico mostra, per ogni regione e per ogni giorno, il totale dei test molecolari e rapidi effettuati, con percentuale dei positivi",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(r2.data, interval 6 hour) AS \"time\",\n  (r2.tamponi_test_antigenico_rapido - r1.tamponi_test_antigenico_rapido)  AS \"Test rapidi\",\n  (r2.tamponi_test_molecolare - r1.tamponi_test_molecolare) AS \"Test molecolari\",\n  ((r2.totale_positivi_test_antigenico_rapido-r1.totale_positivi_test_antigenico_rapido)/(r2.tamponi_test_antigenico_rapido - r1.tamponi_test_antigenico_rapido))*100 AS \"Percentuale test rapidi positivi\",\n  ((r2.totale_positivi_test_molecolare-r1.totale_positivi_test_molecolare)/(r2.tamponi_test_molecolare - r1.tamponi_test_molecolare))*100 AS \"Percentuale test molecolari positivi\"\nFROM covid19.regioni r1, covid19.regioni r2\nwhere r2.denominazione_regione='$Regione' AND r1.denominazione_regione='$Regione' AND r1.data = SUBDATE(r2.data, 1)\nORDER BY r2.data"
    }
   ]
  },
  {
   "title": "Rapporto giornaliero positivi/tamponi per regione - SELEZIONARE REGIONE",
   "type": "graph",
   "description": "Per ogni giorno, per ogni regione, è riportato nel grafico il rapporto fra nuovi positivi e tamponi effettuati (nella stessa giornata).\nResta uno degli indicatori più importanti dell'andamento dell'epidemia, nonostante da solo non possa indicare se ci sia una saturazione del numero dei tamponi, ovvero se il numero di tamponi effettuati sia sufficiente a tracciare tutti o la maggior parte dei casi di contagio.\nUn numero insifficiente significherebbe una rilevante quota sommersa di casi positivi non tracciati.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.nuovi_positivi/(c2.tamponi-c1.tamponi) * 100 as \"Rapporto positivi/tamponi\"\nFROM covid19.regioni c1, covid19.regioni c2\nWHERE c1.data = SUBDATE(c2.data, 1) AND c2.denominazione_regione='$Regione' AND c1.denominazione_regione='$Regione'\n"
    }
   ]
  },
  {
   "title": "Situazione terapie intensive per regione (conteggio posti aggiornato al 03/03/2021) - SELEZIONARE REGIONE",
   "type": "graph",
   "description": "Nel grafico sono riportati, per ogni giorno, per orgni regione, i ricoverati in terapia intensiva.\nSono poi evidenziate due soglie: i posti di terapia intensiva attualmente disponibili e una soglia del 30% dei posti disponibili rappresentante una situazione di emergenza; tali dati si riferiscono alla situazione aggiornata alla data nel titolo del grafico, perciò confronti con la situazione primavarile non hanno senso.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  terapia_intensiva as \"Ricoverati in terapia intensiva\",\n  posti_attuali as \"Posti totali attualmente disponibili\",\n  (posti_attuali/100)*30 as \"Soglia di emergenza del 30% dei posti occupati\"\nFROM regioni, dati_statici\nWHERE denominazione_regione = '$Regione' AND regioni.denominazione_regione = dati_statici.regione"
    }
   ]
  },
  {
   "title": "Decessi giornalieri per regione - SELEZIONARE REGIONE",
   "type": "graph",
   "description": "Il grafico riporta, per ogni giorno, per ogni regione, il numero di decessi registrati legati all'epidemia",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.deceduti-c1.deceduti as \"Decessi giornalieri\"\nFROM covid19.regioni c1, covid19.regioni c2\nWHERE c1.data = SUBDATE(c2.data, 1)\nAND c1.denominazione_regione = '$Regione' and c2.denominazione_regione = '$Regione'"
    }
   ]
  },
  {
   "title": "Positivi giornalieri per regione - SELEZIONARE REGIONE",
   "type": "graph",
   "description": "Il grafico mostra, per ogni giorno, per ogni regione, il numero di positivi registrati.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  nuovi_positivi as \"Positivi giornalieri\"\nFROM covid19.regioni\nWHERE denominazione_regione = '$Regione'"
    }
   ]
  },
  {
   "title": "Media mobile settimanale - incidenza regionale nuovi positivi/100.000 abitanti (basata sugli ultimi 7 giorni)",
   "type": "bargauge",
   "description": "Il grafico mostra, per ogni regione, la media mobile dell'incidenza del numero di nuovi positivi registrati su 100.000 abitanti negli ultimi 7 giorni\n250 casi settimanali/100.000 abitanti è la soglia di allerta più alta.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (SELECT max(data) from regioni) AS \"time\",\n  sum((regioni.nuovi_positivi)/(regdata.popolazione/100000)) as \"Casi giornalieri\",\n  regioni.denominazione_regione\nFROM regioni regioni, dati_statici regdata\nWHERE regioni.denominazione_regione = regdata.regione and regioni.data > SUBDATE((SELECT max(data) from regioni), INTERVAL 7 DAY)\ngroup by regioni.denominazione_regione\nORDER BY `Casi giornalieri` desc"
    }
   ]
  },
  {
   "title": "Proiezione settimanale - incidenza regionale decessi/100.000 abitanti (basata sull'ultimo dato disponibile)",
   "type": "bargauge",
   "description": "Il grafico mostra, per ogni regione, la proiezione settimanale, basata sull'ultimo dato disponibile, dell'incidenza del numero di decessi su 100.000 abitanti.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 63 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  c2.data AS \"time\",\n  MAX((c2.deceduti-c1.deceduti)/(regdata.popolazione/100000))*7 as \"Decessi giornalieri\",\n  c1.denominazione_regione\nFROM covid19.regioni c1, covid19.regioni c2, dati_statici regdata\nWHERE c1.data = SUBDATE(c2.data, 1)  and c2.`data` = (SELECT MAX(data) from nazionale) and c2.denominazione_regione = c1.denominazione_regione and regdata.regione = c2.denominazione_regione\nGROUP by c2.denominazione_regione, c2.data\nORDER BY `Decessi giornalieri` DESC"
    }
   ]
  },
  {
   "title": "Dosi singole di vaccino somministrate sulla popolazione (ultimo dato disponibile)",
   "type": "bargauge",
   "description": "Il grafico mostra, per ogni regione, le dosi di vaccino somministrate su 100.000 abitanti calcolata sull'ultimo dato disponibile.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ultimo_aggiornamento AS \"time\",\n  ((dosi_somministrate)/dati_statici.popolazione)*100 as \"Somministrazioni\",\n  regione\nFROM somministrazioni_summary, dati_statici\nWHERE somministrazioni_summary.area = dati_statici.area\nORDER BY `Somministrazioni` desc"
    }
   ]
  },
  {
   "title": "Percentuale immunizzati sulla popolazione (ultimo dato disponibile)",
   "type": "bargauge",
   "description": "Il grafico mostra, per ogni regione, le persone immunizzate sull'ultimo dato disponibile dell'intera popolazione regionale.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT time, regione, Immunizzazioni from(\nSELECT now() as \"time\", \nregione,\nsomministrazioni_fasce.area as \"areaLoc\",\n((sum(seconda_dose)+(SELECT IF(SUM(prima_dose) IS NULL, 0, sum(prima_dose)) FROM somministrazioni_fasce WHERE fornitore='Janssen' and somministrazioni_fasce.area = areaLoc))/popolazione)*100 as \"Immunizzazioni\"\nFROM somministrazioni_fasce, dati_statici\nWHERE dati_statici.area = somministrazioni_fasce.area\nGROUP BY regione, somministrazioni_fasce.area, popolazione\nORDER BY `Immunizzazioni` desc\n) as t"
    }
   ]
  },
  { "title": "Grafici nazionali", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Rapporto giornaliero positivi/tamponi e numero tamponi",
   "type": "graph",
   "description": "Per ogni giorno, è riportato nel grafico il rapporto fra nuovi positivi e tamponi effettuati (nella stessa giornata), oltre al numero totale di tamponi giornalieri\nResta uno degli indicatori più importanti dell'andamento dell'epidemia, nonostante da solo non possa indicare se ci sia una saturazione del numero dei tamponi, ovvero se il numero di tamponi effettuati sia sufficiente a tracciare tutti o la maggior parte dei casi di contagio.\nUn numero insifficiente significherebbe una rilevante quota sommersa di casi positivi non tracciati.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 90 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n    (c2.tamponi-c1.tamponi) AS \"Tamponi giornalieri\",\n  c2.nuovi_positivi/(c2.tamponi-c1.tamponi) * 100 as \"Rapporto positivi/tamponi\"\n\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)\n"
    }
   ]
  },
  {
   "title": "Tamponi totali e casi totali settimanali (scala logaritmica)",
   "type": "graph",
   "description": "Il grafico mostra, aggregati settimanalmente, i tamponi e i casi positivi registrati di settimana in settimana.\nLa scala logaritmica meglio rende l'idea delle velocità di crescita.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \n  SUBDATE(week2.data, WEEKDAY(week2.data)) as \"time\",\n  (MAX(week2.tamponi) - MAX(week1.tamponi)) as \"Tamponi settimanali\",\n  (MAX(week2.totale_casi) - MAX(week1.totale_casi)) as \"Nuovi positivi settimanali\"\nFROM nazionale week1, nazionale week2\nWHERE SUBDATE(week1.data, WEEKDAY(week1.data)) = SUBDATE(SUBDATE(SUBDATE(week2.data, WEEKDAY(week2.data)), 1), WEEKDAY(SUBDATE(SUBDATE(week2.data, WEEKDAY(week2.data)), 1)))\nGROUP BY time"
    }
   ]
  },
  {
   "title": "Confronto tra rapporto positivi/tamponi e persone immunizzate/100.000 abitanti",
   "type": "graph",
   "description": "Per ogni giorno, è riportato nel grafico il rapporto fra nuovi positivi e tamponi effettuati (nella stessa giornata), oltre al numero totale di persone immunizzate ogni 100.000. A fronte di una campagna vaccinale efficace, il rapporto positivi/tamponi dovrebbe diminuire con un ritardo di almeno 4-5 settimane.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.nuovi_positivi/(c2.tamponi-c1.tamponi) * 100 as \"Rapporto positivi/tamponi\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)\n"
    },
    {
     "rawSql": "SELECT\n  date_add(data_immunizzazione, interval 6 hour) AS \"time\",\n  (immunizzati/(60360000/100000)) as \"Immunizzati/100.000 abitanti\"\nFROM immunizzazioni\n\n"
    }
   ]
  },
  {
   "title": "Confronto tra posti letto occupati e persone immunizzate/100.000 abitanti",
   "type": "graph",
   "description": "Per ogni giorno, è riportato nel grafico il numero di posti letto occupati e il numero totale di persone immunizzate ogni 100.000. A fronte di una campagna vaccinale efficace, il numero di posti letto occupati dovrebbe diminuire con un ritardo di almeno 4-5 settimane.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 99 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  (c2.ricoverati_con_sintomi + c2.terapia_intensiva) AS \"Ricoverati (in reparti ordinari e terapie intensive)\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    },
    {
     "rawSql": "SELECT\n  date_add(data_immunizzazione, interval 6 hour) AS \"time\",\n  (immunizzati/(60360000/100000)) as \"Immunizzati/100.000 abitanti\"\nFROM immunizzazioni\n"
    }
   ]
  },
  {
   "title": "Guariti giornalieri",
   "type": "graph",
   "description": "Il grafico mostra, per ogni giorno, il numero di persone guarite",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n    (c2.dimessi_guariti-c1.dimessi_guariti) AS \"Guariti giornalieri\"\n\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)\n"
    }
   ]
  },
  {
   "title": "Guariti totali da inizio epidemia",
   "type": "graph",
   "description": "Il grafico mostra, con incrementi giornalieri, il totale dei casi guariti da inizio epidemia.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 108 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  dimessi_guariti as \"Guariti totali\"\nFROM covid19.nazionale\nORDER BY data"
    }
   ]
  },
  {
   "title": "Analisi giornaliera guariti/deceduti (ex-casi)",
   "type": "graph",
   "description": "Il grafico riporta, per ogni giorno, il rapporto tra guariti e deceduti per tutti coloro non più considerabili come \"casi contagiati\".\nViene inoltre riportato (in giallo, con scala sulla parte destra del grafico) il numero totale di guariti+deceduti a cui il rapporto fa riferimento",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  (c2.deceduti-c1.deceduti)/((c2.dimessi_guariti-c1.dimessi_guariti)+(c2.deceduti-c1.deceduti))*100 AS \"Percentuale deceduti/ex-casi\",\n  (c2.dimessi_guariti-c1.dimessi_guariti)/((c2.dimessi_guariti-c1.dimessi_guariti)+(c2.deceduti-c1.deceduti))*100 AS \"Percentuale guariti/ex-casi\",\n  (c2.dimessi_guariti-c1.dimessi_guariti)+(c2.deceduti-c1.deceduti) as \"Numero ex-casi\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)\n"
    }
   ]
  },
  {
   "title": "Rapporto giornaliero situazione positivi",
   "type": "graph",
   "description": "Il grafico riporta, per ogni giorno, la ripartizione percentuale tra i pazienti in isolamento domiciliare, i pazienti ricoverati nei reparti ordinari e i pazienti ricoverati nei reparti di terapia intensiva",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 117 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.isolamento_domiciliare/c2.totale_positivi * 100 AS \"Isolamento domicialiare\",\n  c2.ricoverati_con_sintomi/c2.totale_positivi * 100 AS \"Ricoverati con sintomi\",\n  c2.terapia_intensiva/c2.totale_positivi * 100 AS \"Terapia intensiva\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Correlazione giornaliera tra ricoveri (posti letto occupati) e rapporto positivi/tamponi",
   "type": "graph",
   "description": "Questo grafico mostra la correlazione tra due metriche: il rapporto giornaliero tra positivi e tamponi, e il numero di ricoverati presenti giornalmente nelle strutture ospedaliere (quindi il numero di posti letto occupati per giorno)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  (c2.ricoverati_con_sintomi + c2.terapia_intensiva) AS \"Ricoverati (in reparti ordinari e terapie intensive)\",\n  c2.nuovi_positivi/(c2.tamponi-c1.tamponi) * 100 as \"Rapporto positivi/tamponi\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Correlazione tra ricoverati ordinari e in terapia intensiva",
   "type": "graph",
   "description": "Il grafico mostra, per ogni giorno, la correlazione fra i trend di crescita dei ricoverati nei reparti di degenza ordinaria e quelli in terapia intensiva.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 126 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.ricoverati_con_sintomi AS \"Ricoverati in degenza ordinaria\",\n  c2.terapia_intensiva AS \"Terapia intensiva\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Ospedalizzazioni giornaliere",
   "type": "graph",
   "description": "Il grafico riporta a livello nazionale, per ogni giorno, il numero dei pazienti ricoverati negli ospedali nei riparti ordinari e di terapia intensiva",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.ricoverati_con_sintomi AS \"Ricoverati con sintomi\",\n  c2.terapia_intensiva AS \"Terapia intensiva\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Confronto tra variazione giornaliera di ricoveri ordinari e terapie intensive",
   "type": "graph",
   "description": "Il grafico mostra, per ogni giorno, la variazione rispetto al giorno precedente di ricoverati in reparti ordinari e di terapia intensiva, al fine di poter confrontare le due quantità",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  (c2.terapia_intensiva-c1.terapia_intensiva) AS \"Variazione ricoveri in terapia intensiva rispetto al giorno precedente\",\n  (c2.ricoverati_con_sintomi-c1.ricoverati_con_sintomi) AS \"Variazione ricoveri ordinari rispetto al giorno precedente\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Ricoveri giornalieri in terapia intensiva (con soglie emergenziali)",
   "type": "graph",
   "description": "Il grafico riporta, per ogni giorno, il numero di pazienti ricoverati nei reparti di terapia intensiva.\nVengono mostrati anche due valori, equivalenti al 30% e al 40% delle terapie intensive occupate, considerate dal Governo come soglie d'emergenza.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 144 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  terapia_intensiva as \"Ricoverati in terapia intensiva\",\n  (select floor(sum(posti_attuali)*0.3) from dati_statici ) as \"Soglia del 30% delle terapie intensive occupate\",\n  (select floor(sum(posti_attuali)*0.4) from dati_statici ) as \"Soglia del 40% delle terapie intensive occupate\"\nFROM nazionale"
    }
   ]
  },
  {
   "title": "Variazione giornaliera di ricoveri in terapia intensiva",
   "type": "graph",
   "description": "Il grafico mostra, per ogni giorno, la variazione (positiva o negativa) del numero di pazienti in terapia intensiva rispetto al giorno precedente",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 144 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  (c2.terapia_intensiva-c1.terapia_intensiva) AS \"Variazione ricoveri in terapia intensiva rispetto al giorno precedente\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Confronto giornaliero tra ricoveri in terapia intensiva e decessi",
   "type": "graph",
   "description": "Nel grafico si osserva, per ogni giorno, su scale diverse, il confronto tra l'andamento dei ricoveri in terapia intensiva e quello dei decessi",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "none", "label": "Decessi giornalieri" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.deceduti-c1.deceduti as \"Decessi giornalieri\",\n  c2.terapia_intensiva as \"Ricoveri in terapia intensiva\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Nuovi ingressi giornalieri in terapia intensiva (dati disponibili dal 03/12/2020)",
   "type": "graph",
   "description": "Nel grafico sono riportati, per ogni giorno a partire dal 03/12/2020, i nuovi ingressi in terapia intensiva, indipendentemente dalle uscite",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  ingressi_terapia_intensiva as \"Nuovi ingressi giornalieri in terapia intensiva\"\nFROM nazionale"
    }
   ]
  },
  {
   "title": "Decessi giornalieri",
   "type": "graph",
   "description": "Il grafico riporta, per ogni giorno, il numero di decessi registrati legati all'epidemia",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 162 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.deceduti-c1.deceduti as \"Decessi giornalieri\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Decessi giornalieri (scala logaritmica)",
   "type": "graph",
   "description": "Il grafico riporta, per ogni giorno, su scala logaritmica, il numero di decessi registrati legati all'epidemia",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 162 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(c2.data, interval 6 hour) AS \"time\",\n  c2.deceduti-c1.deceduti as \"Decessi giornalieri\"\nFROM covid19.nazionale c1, covid19.nazionale c2\nWHERE c1.data = SUBDATE(c2.data, 1)"
    }
   ]
  },
  {
   "title": "Test e positivi giornalieri per tamponi rapidi e molecolari",
   "type": "graph",
   "description": "Il grafico mostra, per ogni giorno, il totale dei test molecolari e rapidi effettuati a livello nazionale, con percentuale dei positivi",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 171 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(r2.data, interval 6 hour) AS \"time\",\n  (r2.tamponi_test_antigenico_rapido - r1.tamponi_test_antigenico_rapido)  AS \"Test rapidi\",\n  (r2.tamponi_test_molecolare - r1.tamponi_test_molecolare) AS \"Test molecolari\",\n  ((r2.totale_positivi_test_antigenico_rapido-r1.totale_positivi_test_antigenico_rapido)/(r2.tamponi_test_antigenico_rapido - r1.tamponi_test_antigenico_rapido))*100 AS \"Percentuale test rapidi positivi\",\n  ((r2.totale_positivi_test_molecolare-r1.totale_positivi_test_molecolare)/(r2.tamponi_test_molecolare - r1.tamponi_test_molecolare))*100 AS \"Percentuale test molecolari positivi\"\nFROM covid19.nazionale r1, covid19.nazionale r2\nwhere r1.data = SUBDATE(r2.data, 1)\nORDER BY r2.data"
    }
   ]
  },
  {
   "title": "Rapporto giornaliero tra casi positivi emersi da sospetto diagnostico e da attività di screening (REPORT NON PIÙ ATTIVO)",
   "type": "graph",
   "description": "Il grafico mostra, per ogni giorno (a partire da quando i dati sono disponibili) un confronto tra la percentuale di casi positivi al tampone emersi da attività clinica (sospetto diagnostico) e la percentuale di casi positivi emersi da indagini e test, pianificati a livello nazionale o regionale (screening).\nUn migliore tracciamento dovuto allo screening aumenta la possibilità di rilevare e isolare positivi asintomatici.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 171 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  casi_da_sospetto_diagnostico/totale_casi * 100 as \"Percentuale positivi da sospetto diagnostico\",\n  casi_da_screening/totale_casi * 100 as \"Percentuale positivi da screening\"\nFROM covid19.nazionale\n"
    },
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  100 as \"Dati non disponibili fino al 24/06/2020\"\nFROM covid19.nazionale\nWHERE data < (\"2020-06-25\") OR data > (\"2020-12-02\")"
    }
   ]
  },
  {
   "title": "Trend decessi totali da inizio epidemia",
   "type": "graph",
   "description": "Il grafico riporta il numero totale di decessi registrati dall'inizio dell'epidemia ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 180 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  deceduti as \"Decessi\"\nFROM nazionale"
    }
   ]
  },
  {
   "title": "Trend nazionale contagi (totale casi da inizio epidemia)",
   "type": "graph",
   "description": "Nel grafico è riportato il numero totale di casi di contagio tracciati dall'inizio dell'epidemia",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 180 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  totale_casi as \"Casi totali\"\nFROM covid19.nazionale\nORDER BY data"
    }
   ]
  },
  {
   "title": "Trend nazionale contagi (nuovi casi rilevati giornalieri)",
   "type": "graph",
   "description": "Il grafico mostra, per ogni giorno, il numero di nuovi casi rilevati",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  date_add(data, interval 6 hour) AS \"time\",\n  nuovi_positivi as \"Positivi giornalieri\"\nFROM covid19.nazionale"
    }
   ]
  },
  {
   "title": "Casi totali da inizio epidemia",
   "type": "grafana-worldmap-panel",
   "description": "La cartina mostra a livello provinciale l'impatto del virus, mostrando i casi totali da inizio epidemia.\nIn rosso le province che hanno registrato più di 40.000 casi, in arancione le province che hanno registrato tra i 20.000 e i 40.000 casi, in giallo le province che hanno registrato tra i 5.000 e i 20.000 casi, e in verde le province che hanno registrato meno di 5.000 casi da inizio epidemia",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 198 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT `long`, lat, denominazione_provincia, max(totale_casi) as tot\nFROM covid19.province\nwhere `long`<>0\n  and  $__timeFilter(data)\ngroup by `long`, lat, denominazione_provincia\norder by `long`, lat, denominazione_provincia"
    }
   ]
  },
  {
   "title": "Positivi giornalieri",
   "type": "grafana-worldmap-panel",
   "description": "La mappa mostra, per ogni regione, l'ultimo numero disponibile di casi positivi totali ",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 221 },
   "valueName": "total",
   "targets": [
    {
     "rawSql": "SELECT `long`, lat, denominazione_regione, (isolamento_domiciliare + ricoverati_con_sintomi + terapia_intensiva) as tot\nFROM covid19.regioni\nwhere `long`<>0\n  and data = (SELECT max(data) FROM nazionale)\norder by `long`, lat, denominazione_regione"
    }
   ]
  },
  {
   "title": "Guida alla consultazione",
   "type": "text",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 244 },
   "options": {
    "content": "# Guida alla consultazione\n\n#### Grafici regionali/nazionali\nLa prima sezione di grafici contiene i grafici regionali. I dati di questi grafici fanno riferimento a province e regioni: selezionando una regione dal menu in alto, questi grafici si aggiorneranno mostrando i dati relativi alla regione selezionata.  \nIl secondo gruppo, invece, presenta grafici con i dati nazionali, non divisi per regioni.\n\n#### Grafici totali/giornalieri\nI grafici in generale si dividono in \"totali\" e \"giornalieri\". Nei grafici \"totali\", per ogni giorno vengono riportati valori aggregati dati dalla somma di tutti i valori giornalieri da inizio epidemia; nei grafici \"giornalieri\", vengono invece riportati i dati raccolti in ogni singolo giorno.  \nPerciò, ad esempio, se in un grafico \"giornaliero\" i primi 3 valori fossero 3, 7 e 18 (il che significa un valore 3 relativo al primo giorno, un valore 7 relativo al secondo giorno e un valore 18 relativo al terzo giorno), un equivalente grafico \"totale\", che volesse esprimere lo stesso dato, dovrebbe riportare il valore 3 nel primo giorno (non essendoci valori precedenti), un valore 10 nel secondo giorno (che è la somma dei valori dei primi due giorni) e un valore 28 nel terzo giorno (che è la somma dei valori dei primi 3 giorni).\n\n#### Consultazione di un grafico \nOgni grafico è corredato di un titolo e una descrizione (visualizzabile passando il puntatore del mouse sulla \"i\" che si vede nell'angolo in alto a sinistra di ogni grafico).  \nSpostando il puntatore del mouse lungo il grafico, si possono visualizzare i valori precisi riportati nel grafico stesso.  \nCliccando su un punto di un grafico e trascinando il mouse, si può fare lo zoom dell'area di grafico di proprio interesse (un particolare periodo, ad esempio): per tornare alla visualizzazione classica si può ricarica la pagina https://covid-italy.marcogasparri.com. Inoltre, in alto a destra, è presente un tool per cambiare l'intervallo temporale preso in esame da tutti i grafici della pagina.  \n\n\n  --  \n    \n*NOTA*: eventuali metriche con la dicitura \"[BETA]\" nel titolo rappresentano metriche sperimentali in corso di valutazione.\n  \n*DISCLAIMER*: i dati originali si basano su quelli forniti dal Dipartimento di Protezione Civile, perciò in caso di errori in quei dati potrebbero esserci errori propagati sulle statistiche.  \nInoltre, le analisi sono frutto di elaborazioni non professionali, che cercano di dare però una visione il più possibile completa della realtà: in caso di obiezioni, vi chiedo gentilmente di contattarmi e inviarmi segnalazioni all'indirizzo mg@marcogasparri.com"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Contatti",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 258 },
   "options": {
    "content": "# Contatti\n\nPer segnalazioni, proposte di metriche/grafici da aggiungere, o altre comunicazioni, scrivere un'e-mail a: mg@marcogasparri.com         "
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Privacy policy",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 261 },
   "options": {
    "content": "<span style=\"text-align:center; margin: 0 auto;\">La policy relativa a privacy e cookie è visualizzabile <a href=\"https://marcogasparri.com/privacy.html\" target=\"blank\">QUI</a></span>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  }
 ]
}